### ISSUE TITLE
Build release locally or on CI machine

### ISSUE THREAD

**Issue by Linuus** [boldpoker/edeliver#101]
Hi!

I have two questions

**1 Build on my local laptop**
I'm experimenting a bit with edeliver and I try to build releases locally on OSX but I have some issues.

My edeliver config looks like this:
```sh
#!/usr/bin/env bash

APP="phoenix-chat" # name of your release

BUILD_HOST="localhost" # host where to build the release
BUILD_USER="linus" # local user at build host
BUILD_AT="/tmp/erlang/phoenix-chat/builds" # build directory on build host

STAGING_HOSTS="localhost" # staging / test hosts separated by space
STAGING_USER="linus" # local user at staging hosts
TEST_AT="/tmp/erlang/staging/phoenix-chat" # deploy directory on staging hosts. default is DELIVER_TO

PRODUCTION_HOSTS="localhost" # deploy / production hosts separated by space
PRODUCTION_USER="linus" # local user at deploy hosts
DELIVER_TO="/tmp/erlang/staging/phoenix-chat" # deploy directory on production hosts
```

When I run `mix edeliver build release` it outputs
```sh
BUILDING RELEASE OF PHOENIX-CHAT APP ON BUILD HOST

-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: linus@localhost
-----> Resetting remote hosts to 02bbbc8a295542146aef4e347dcbdc5fd0aadd69
-----> Cleaning generated files from last build
-----> Fetching / Updating dependencies
using mix to fetch and update deps
rebar for mix was built already
zsh:15: command not found: mix

A remote command failed on:

  linus@localhost

Output of the command is shown above and the command executed
on that host is printed below for debugging purposes:

FAILED with exit status 127:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd /tmp/erlang/phoenix-chat/builds
    if [ "mix" = "rebar" ]; then
      echo "using rebar to fetch and update deps"
      ./rebar  update-deps get-deps
    elif [ "mix" = "mix" ]; then
      echo "using mix to fetch and update deps"
      if [ ! -f ~/.mix/rebar ]; then
        APP="phoenix-chat" MIX_ENV="prod" mix local.rebar --force
      else
        echo "rebar for mix was built already"
      fi
      APP="phoenix-chat" MIX_ENV="prod" mix local.hex --force
      APP="phoenix-chat" MIX_ENV="prod" mix deps.get
    fi
```

However, if I manually run `ssh linus@localhost` I can execute the mix command. Why wouldn't the script find it?

**2 Build on CI machine**
This is kind of related to the above.

Is it possible to build the release on my CI machine (Travics-CI) and avoid maintaining a build machine (both the CI machine and the actual hosts are running Ubuntu)? The releases would be uploaded to S3 or something after being built.

**Comment by bharendt** [comment]
Hi. I think `mix` is not found in your case because it is not in the default `$PATH` and neither set in the `~/.profile`, which is read when edeliver executes commands on the build host. If you login using ssh and execute the `mix` command separately, the login shell is executed, while when using edeliver only the build commands are executed. Your login shell loads also the `/etc/profile`, `/etc/zprofile`, `$ZDOTDIR/.zprofile`, `$ZDOTDIR/.zshrc` etc which might set the path to the `mix` binary, especially if you use something like [exenv](https://github.com/mururu/exenv). See also: #75.
But anyway, it does not make so much sense to use edeliver when builing on localhost. You might want to just run `mix release` in that case. But if your deploy server runs a different operating system, you must also build the release on that system. If your ci server also runs ubuntu, you have ssh access, it has a known host-name or fixed ip and erlang and elixir is installed, you can also use that host as build host, or even on one of the deploy hosts if it is ok for you, that the sources are pushed there while building and that erlang and edeliver needs to be installed.

**Comment by Linuus** [comment]
Yeah, I just want to experiment with it a bit before I decide to try it on my real projects :) To avoid starting servers I just wanted to try and build it on my local machine. Fixing the path in `.profile` fixed the mix issues. Thanks!

**Comment by lessless** [comment]
@bharendt actually there is a situation when using edeliver on the local machine is a preferable way: it occurs when `local` machine is a CI server. 
Then edeliver ease hot-upgrade burden.

**Comment by mkaravaev** [comment]
@Linuus have you've been succeed with Travis CI and edeliver integration?

**Comment by Linuus** [comment]
@mkaravev no, sorry, I haven't looked at it since this issue.
