### ISSUE TITLE
[Proposal]: Add release package upload progress display

### ISSUE THREAD

**Issue by developerworks** [boldpoker/edeliver#106]
Like this: 
![upload progress display](https://camo2.githubusercontent.com/eec33881a73d111bd7fbf6e143ab92e2215877a6/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f324e336e3434305330643253326e3337316a30472f70726f67726573735f6261722e676966)

https://github.com/henrik/progress_bar

**Comment by bharendt** [comment]
Yes, that would be nice. But it would be not so easy to implement or even not possible at all because edeliver uploads the release / upgrade file concurrently to all deploy hosts and in bash it is not possible to report data back from a process started in the background to the process which started it (without using temp files). That is the main _problem_ but the _difficulty_ is in addition, that edeliver supports (at the moment) three release store types (local, ssh-location and amazon s3 storage) and it would be required to implement the progress bar for each of them and all future types. But as a start we could maybe display a progress bar when using the local release store (any maybe s3) and if the release is uploaded to a single host and the `--verbose` option is used.
