### ISSUE TITLE
Failed to find local release store

### ISSUE THREAD

**Issue by Gacnt** [boldpoker/edeliver#108]
This is my config:
```
#!/usr/bin/env bash

APP="pugit" # name of your release

BUILD_HOST="xxx" # host where to build the release
BUILD_USER="root" # local user at build host
BUILD_AT="/tmp/erlang/pugit/builds" # build directory on build host // Confirmed Existance

STAGING_HOSTS="xxx" # staging / test hosts separated by space
STAGING_USER="root" # local user at staging hosts
TEST_AT="/test/pugit" # deploy directory on staging hosts. default is deliver_to

PRODUCTION_HOSTS="xxx" # deploy / production hosts separated by space
PRODUCTION_USER="root" # local user at deploy hosts
DELIVER_TO="/home/wowserver/pugit" # deploy directory on production hosts

RELEASE_DIR="$BUILD_AT/rel/$APP"

```
I then ran:

```
MIX_ENV=prod mix phoenix.digest
MIX_ENV=prod mix compile
mix edeliver build release
```

All is well and its built, then I try to run

```
MIX_ENV=prod mix edeliver deploy release to production
```

Which fails with:
```
-----> Authorizing hosts
ls: .deliver/releases/pugit_*.*.tar.gz: No such file or directory
No *(s) found in local release store.
You can build one with the ./edeliver build * task.
```

**Comment by bharendt** [comment]
If you run `mix edeliver build release` edeliver should copy the generated release to the release store.
If it doen't, we would need some more information to be able to help:

- 1) What is the output of the `edeliver build release` command? 
- 2) Does it show something like `---> Copying Release ...` at the last line?
- 3) What is the output of the copy step if you run that command using the `--verbose` option? 
- 4) Are there any releases at `.deliver/releases/`?
- 5) Is there a generated release on the build host at `/tmp/erlang/pugit/builds`?
- 6) Which edeliver version are you using and which exrm version?

Btw: running
```bash
MIX_ENV=prod mix phoenix.digest
MIX_ENV=prod mix compile
```
on your local development machine does not affect the edeliver build since that runs on the build host.
If you want to run `mix phoenix.digest` while building the release on the build host, you can use e.g. an
an edeliver pre hook. You can find more details on the ["Run additional build tasks" wiki page](https://github.com/boldpoker/edeliver/wiki/Run-additional-build-tasks).

**Comment by GildedHonour** [comment]
@bharendt where should I run "mix edeliver build release " -- locally? on a server? in what folder?
