### ISSUE TITLE
Checking out previous version from git fails

### ISSUE THREAD

**Issue by dustinfarris** [boldpoker/edeliver#111]
I want to see what happens when the local releases directory is empty (e.g. a fresh clone) and then do an upgrade with edeliver.

Using the recommended autoversion:

```
AUTO_VERSION="commit-count+git-revision+branch-unless-master"
```

I get this when doing `mix edeliver upgrade`:

```
...
-----> Checking whether installed version 0.0.1+7-6b333dd is in release store
ls: .deliver/releases/example_*.*.tar.gz: No such file or directory
-----> Building the upgrade from version 0.0.1+7-6b333dd
-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: builder@build.app.industrymaps.com
-----> Resetting remote hosts to a1823da3a99e8b20163a129866e7934f59d978b1
-----> Cleaning generated files from last build
-----> Checking out 0.0.1+7
error: pathspec '0.0.1+7' did not match any file(s) known to git.
```

It is trying to check out the wrong part of the version string.  Is there a way to indicate which part of the version is the sha?

**Comment by bharendt** [comment]
Edeliver assumes that there is an old release in the release store which is needed to build the hot code upgrade. That's why it keeps track of the built releases in the release store. As fallback it tries to build the old one if it is not available.
Edeliver does not know whether your old release version contains a git hash as metadatata. The old release version could contain anything as metadata as long it is compliant with the [semantic versioning](http://semver.org) rules. As fallback it tries to build a version from a tag that is equal to the running version. This works only if you are not using auto-versioning (because metadata are appended to the version). If you are using auto-versioning and the old release is not available you can try to pass the `--from=<git-revision>` option, in your case `--from=6b333dd`. I think this should work even if that option is only documented for the `build upgrade` task, not (yet) for the `upgrade` task.

**Comment by dustinfarris** [comment]
@bharendt ok that makes sense, thanks for the explantation.  I wonder if this is something that can be improved on—if there is a way to detect that auto-versioning is enabled so grab the sha instead of grabbing a tag.

**Comment by bharendt** [comment]
Yes, that could be improved. But it would be not so easy to implement because the version metadata can contain anything. It is hard to decide whether e.g. in an old version `1.0.1+badcode` the metadata `badcode` would be a valid git hash or a branch name or just something else. It would be requried to check also the old version of the edeliver config (and its `AUTO_VERSION` value) to have a reasonable suspicion that the old version would contain a git revision.

**Comment by dustinfarris** [comment]
@bharendt good points, almost seems worth it to tag every build.  Otherwise would have to keep some kind of canonical log in the repo that keeps track of every version/branch/sha that is built

**Comment by dustinfarris** [comment]
what about just force appending the sha to the end of the metadata as a last step internally?

so if the user's AUTO_VERSION is commit-count+git-revision+branch-unless-master, internally that becomes commit-count+git-revision+branch-unless-master+git-revision

Then we know it's always at the end

**Comment by dustinfarris** [comment]
So i am doing this to see if it works, so far it does:

```sh
# .deliver/config
AUTO_VERSION=git-revision
```

In a script:

```bash
#!/bin/bash

ENVIRONMENT=${1:-staging}
CURRENT_SHA=`mix edeliver version $ENVIRONMENT | grep -o "^  response: .*" | head -n1 | cut -f2- -d'+' | cut -c1-7`

mix edeliver build upgrade --from=$CURRENT_SHA
mix edeliver deploy upgrade to $ENVIRONMENT
```

**Comment by bharendt** [comment]
Yes, maybe we could just split the version into major/minor/patch and metadata and consider metadata matching 7 digit valid hex values as git revision and then try whether that commit exists and if not, trying to build the major/minor/patch version from a tag. That check could be added somewhere around [this line](https://github.com/boldpoker/edeliver/blob/652a699af71542fc7774f948f0fdb23580c71748/strategies/erlang-upgrade#L140) in the `upgrade` task.

**Comment by bharendt** [comment]
Closing this issue because it will be obsolete in [version 2.0](https://github.com/boldpoker/edeliver/milestone/1). Building the old release from sources (which is required to build the live upgrade) will be obsolete and the data of the running release will be used to build the upgrade. See #142.
