### ISSUE TITLE
Auto-versioning issue

### ISSUE THREAD

**Issue by insiderq** [boldpoker/edeliver#119]
I've configured auto-versioning with `AUTO_VERSION=commit-count`
First time building with `MIX_ENV=prod mix edeliver build release` release was :ok, but the second i've got the following error.
I assume that behavior is not supposed to be there.

```BUILDING RELEASE OF INVOICES APP ON BUILD HOST

-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: root@host
-----> Resetting remote hosts to 3e**b
-----> Skipped cleaning generated files from last build
-----> Copying 'config/prod.secret.exs' file to build host
-----> Fetching / Updating dependencies
-----> Compiling sources (skipping cleaning)
-----> Detecting exrm version
-----> Generating release
Failed to detect generated release version at:
root@host:/root/build/rel/my_proj/releases/

Detected several releases:
 0.0.1+6
 0.0.1+8
Please rerun with RELEASE_VERSION=x environment variable set.```

**Comment by bharendt** [comment]
This is usually caused either by setting `RELEASE_VERSION` in the edeliver config which __must not be set in the config__ (see #44 and #115) or by an incorrect configuration of the `GIT_CLEAN_PATHS` config. This __must contain at least the the__ `rel` __directory__ containing the built releases. This directory must contain only one built release (when the build is finished), because it is not possible to detect which release would be the more recent one because generic version names can be used (at least as metadata) for releases. See #36.

**Comment by insiderq** [comment]
Ok, thanks. It works
