### ISSUE TITLE
Tail, illegal offset

### ISSUE THREAD

**Issue by kuon** [boldpoker/edeliver#126]
When running edeliver upgrade, I have the following error

```
-----> Detecting release versions on staging hosts
tail: illegal offset -- + # Error here
-----> Deploying 1 releases to offline hosts
-----> Building the release
-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
...
```

Running on FreeBSD 10.3

**Comment by bharendt** [comment]
edeliver tries to display only the expected output of a node command by [removing unexpected leading lines using the `tail` command](https://github.com/boldpoker/edeliver/blob/f62cfbd4e6c83614636f2659cb5c299a75e31e49/libexec/erlang#L816). This is required because the nodes boot script generated by exrm prints [some additional information depending on the exrm version](https://github.com/bitwalker/exrm/commit/6df2765b27e29dc910be959a49385951d68d83f9). If you update exrm, that additional line which was printing the release version should be removed and the edeliver tail command should not need to use the `+` argument for the `tail` command. But if you have time, you could try why this does not work on FreeBSD. Actually [it looks like it's `tail` binary supports the `+` argument](https://www.freebsd.org/cgi/man.cgi?query=tail). But maybe that version expects a space before the `+` sign.

**Comment by kuon** [comment]
I found the issue, on FreeBSD, `wc -l` (https://github.com/boldpoker/edeliver/blob/f62cfbd4e6c83614636f2659cb5c299a75e31e49/libexec/erlang#L813) will return `       1` (with spaces), and then `tail -n+       1` will be run, which fails. So the problem is `wc`. This can be fixed by triming `wc` output: `wc -l | tr -d ' \t'`.

**Comment by bharendt** [comment]
Actually the [check that test whether there is more than one line of output](https://github.com/boldpoker/edeliver/blob/f62cfbd4e6c83614636f2659cb5c299a75e31e49/libexec/erlang#L814) should still work, even if the number returned by `wc -l` contains leading spaces, e.g like this:

```bash
[[ "    2" -gt 1 ]] && echo "true" || echo "false" 
true
[[ "    1" -gt 1 ]] && echo "true" || echo "false"
false
```
But I think in that line is the actual error: `output_lines` was not used correctly as variable (the leading dollar sign was missing). But I will remove leading whitespaces as you recommended in addition.

**Comment by kuon** [comment]
It's not the test that fails, but the input to tail, if you have space between `+` and the line number, it fails.

**Comment by bharendt** [comment]
If there is only one output line, like in your case an for recent exrm versions, `tail` should [not be used at all](https://github.com/boldpoker/edeliver/blob/b8fba21d9ee555c60e883f84c2d5b9cf8f01b344/libexec/erlang#L814). Whitespaces after the `+` are removed in addition now.
