### ISSUE TITLE
Strategy for secrets

### ISSUE THREAD

**Issue by colindensem** [boldpoker/edeliver#13]
I like what I see, thankyou... Just experimenting to deploy a phoenix application. Still very green to it all.

Within this phoenix app, there is a config/prod.secret.exs. I'm not commiting this file to the git store as it's full of 'secrets'. Instead and traditionally, before a build/release (cap/ruby) we'd link this and similar into the checkout. e.g. upload folders and so on.

Presently the mix release step fails as this file isn't present. 

In Capistrano, we'd have the symlink dir and files step. I'm wondering if you had or are intending on a strategy for this scenario?

---
For the moment I've added a secrets file with ENV, so:
config :app_name, AppName.Endpoint,
  secret_key_base: System.get_env("APP_NAME_SECRET_KEY_BASE")

**Comment by bharendt** [comment]
Yes, one option would be to __link the config__ file __before building__.
If the config is required during the build process, the config can be
linked from a custom __pre compile hook__ in the `.deliver/config` file:

    pre_erlang_clean_compile() {
      __remote "
        set -e
        [ -f ~/.profile ] && source ~/.profile
        cd $BUILD_AT $SILENCE
        ln -s /etc/secret.exs config/prod.secret.exs
      "
      
    }

If the config is required just __before packaging the release__ a custom __exrm 
plugin__ / task can be used, like this e.g. in `lib/tasks/link_config.ex`

    defmodule ReleaseManager.Plugin.LinkConfig do
      use ReleaseManager.Plugin

      def before_release(%Config{env: :prod}) do
        debug "Linking config file"
        File.ln_s("/etc/secret.exs", "config/prod.secret.exs")
      end
      def before_release(_), do: nil

      def after_release(_), do: nil

      def after_cleanup(_), do: nil
    end


When using a link, a __dummy config should be present on the build host__ otherwise
the link process might fail because of the missing destination, and of course a __production config on each production host__. 

A more __general approach__ is to link the `releases/[version]/vm.args` file to be able to 
__change__ also the name and cookie of the node and __other vm args__, like enabling kernel poll with
the `+K true` option or __including aditional config files__ by appending `-config` arguments.
e.g like adding this in `lib/tasks/link_vm_args.ex`:

    defmodule ReleaseManager.Plugin.LinkVMARgs do
      use ReleaseManager.Plugin
      alias  ReleaseManager.Utils


      def before_release(_), do: nil

      def after_release(%Config{env: :prod, version: version, name: name}) do
        debug "Linking vm.args file"
        vmargs_path = Utils.rel_dest_path(Path.join([name, "releases", version, "vm.args"]))
        if vmargs_path |> File.exists?, do: vmargs_path |> File.rm
        File.ln_s(Path.join(["/", "etc", name, "vm.args"]), vmargs_path)
      end
      def after_release(_), do: nil

      def after_cleanup(_), do: nil
    end
  
The vm config in `/etc/my-app/vm.args` might then look like that:

    ## Use custom node name
    -name custom-node-name@host-name

    ## User different cookie as the default one
    -setcookie my-secret-cookie-instead-of-default

    ## Enable kernel poll 
    +K true

    ## Increase number of concurrent ports/sockets
    -env ERL_MAX_PORTS 8192

    ## Use additional configs which can also override
    ## the default values from the releases/[version]/sys.config

    -config /etc/my-database-secrets.config
    -config /etc/my-app-configs.config
    -config /etc/my-logging-configs.config


Another option would be to __remotely copy the config__ from an edeliver __pre hook__, e.g. like this:

    pre_erlang_clean_compile() {
      if [ "$DEPLOY_ENVIRONMENT" = "production" ]; then
        scp ~/prod.secret.exs $BUILD_USER@$BUILD_HOST:$BUILD_AT/config/prod.secret.exs
      fi      
    }

If there are __other ideas__ how to embed a config, which might also be different for different production hosts then I would be __happy to hear them__. 

Maybe we could __add__ an `--link-vm-args=<destination>` option or an `--link-sys-config=<destination>` __option to edeliver__ if this is a common usecase / requirement.

**Comment by colindensem** [comment]
Brilliant answer thank you. I think the above covers all my possible needs at this stage.

Certainly the  link the config file before building is in keeping with current capistrano/12factor thinking.

**Comment by bharendt** [comment]
Added options `LINK_VM_ARGS=/path/to/vm.args` and/or `LINK_SYS_CONFIG=/path/to/sys.config` in 3f302fe38da40e5e61db9ee14ffce42bd75c0cb4

**Comment by linjunpop** [comment]
My solution is

```
pre_erlang_get_and_update_deps() {
  if [ "$TARGET_MIX_ENV" == "prod" ]; then
    status "Copying 'config/prod.secret.exs' file to remote server"
    scp ./config/prod.secret.exs $BUILD_USER@$BUILD_HOST:$BUILD_AT/config/prod.secret.exs
  fi
}
```

**Comment by linjunpop** [comment]
My solution for Phoenix project is

```
pre_erlang_get_and_update_deps() {
  if [ "$TARGET_MIX_ENV" == "prod" ]; then
    status "Copying 'config/prod.secret.exs' file to remote server"
    scp ./config/prod.secret.exs $BUILD_USER@$BUILD_HOST:$BUILD_AT/config/prod.secret.exs
  fi
}
```

**Comment by bharendt** [comment]
@linjunpop: Thanks for sharing that info. [I added it to the wiki](https://github.com/boldpoker/edeliver/wiki/Embed-Secrets---Credentials-into-the-Release).
