### ISSUE TITLE
edeliver commands behave inconsistently depending on option flags

### ISSUE THREAD

**Issue by walterbm** [boldpoker/edeliver#133]
I ran into a weird issue in the final stage of deploying my app with edeliver. Building a release and updating worked as expected but the `start` command fails except when I pass an option flag. 

Here's the output from running `mix edeliver start staging`:
```
EDELIVER API WITH START COMMAND
-----> starting staging servers
staging node:
  user    : deploy
  host    : 198.199.73.246
  path    : /opt
  response: sh: 2: source: not found
sh: 5: bin/api: not found
sh: 6: [[: not found
sh: 24: [[: not found
sh: 31: [[: not found
sh: 48: bin/api: not found
START DONE!
```
But the staging app does not actually start. In the staging server I can navigate to `/opt/api/bin/api` and manually start the app without any issues so the `bin/api: not found` error is incorrect. 

However, when I run `mix edeliver start staging -V` I get the following output: 
```
EDELIVER KRATOS_API WITH START COMMAND
-----> starting staging servers
staging node:
  user    : deploy
  host    : 198.199.73.246
  path    : /opt
  response: sh: 2: source: not found
sh: 6: [[: not found
sh: 24: [[: not found
sh: 31: [[: not found
START DONE!
```
And the staging app starts successfully. 

Likewise `mix edeliver stop staging` does not actually stop the app but `mix edeliver stop staging -V` does.

I'm not exactly sure what is causing this inconsistent behavior. Maybe the `source: not found` and `[[: not found` errors are treated differently based on the flag?  The only obvious difference between the two outputs is that `sh: 5: bin/api: not found` does not appear when the `-V` flag is passed into the command. Passing the `-D` flag leads to the same result as `-V`.

I know this may not be enough information to debug the behavior so please let me know what I can do to narrow down the cause of the error.

**Comment by bharendt** [comment]
Your problem looks like it would be related to #124: your default shell is neither `bash` nor `zsh`. Double brackets in conditions `[[ ... ]]` are not supported by all shells. Can you tell which os you are using and which shell is the default shell, e.g. by executing `echo $SHELL` or `echo $0` after a login?

**Comment by walterbm** [comment]
@bharendt Both my build and deploy environments are running Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-57-generic x86_64) with `bash` as the default shell. These are DigitalOcean Ubuntu Elixir 14.04 droplets if that matters.

My local dev environment is running OS X El Capitan 10.11.6 and also uses `bash` as the default shell.

**Comment by bharendt** [comment]
Are you sure? The error message `sh: 2: source: not found` also indicates that a different [shell without `source` support is used](http://stackoverflow.com/questions/13702425/source-command-not-found-in-sh-shell). It is also possible that [bash is your login shell but not the default shell](http://unix.stackexchange.com/questions/292596/why-is-the-default-shell-on-my-ubuntu-14-04-bash).  You can test that maybe by executing the following command:

 ```bash
 source .deliver/config
 ssh "${PRODUCTION_USER}@your-production-host" 'echo "SHELL=$SHELL, \$0=$0"'
 ```

**Comment by walterbm** [comment]
That was it! Thank you! The login shell is `bash` but the default shell is `sh`. Here's the output from executing that command:
```
ssh "${STAGING_USER}"@xxx.xxx.xxx.xxx 'echo "SHELL=$SHELL, \$0=$0"'
>> SHELL=/bin/sh, $0=sh
```
But the one thing I still don't understand is why did the command succeed when I passed in `-V` or `-D`? This is already a strange edge case of using an incompatible shell so I'm just asking out of curiosity.

**Comment by bharendt** [comment]
This can be explained as follows:

[`libexec/edeliver:828-843`](https://github.com/boldpoker/edeliver/blob/7b5a5f7915a167e5fd9ccf168c312b801d579404/libexec/erlang#L828-L843)

```sh
828: [ -f ~/.profile ] && source ~/.profile
829: set -e
830: cd ${_app_path}/${APP} $SILENCE
831: output_lines=\"\$(bin/${APP} ping | wc -l | tr -d ' ')\"
832: if [[ \"\$output_lines\" -gt 1 ]]; then
...
843: bin/${APP} start | \$output_filter_command \$output_filter_command_options
```

First edeliver sources the `~/.profile` file, if it exists. But tilde expansion is not supported and the source command does not exist. That's why you always see `sh: 2: source: not found`. So that line needs to change to: `[ -f "${HOME}/.profile" ] && . "${HOME}/.profile"`.  The second line `set -e` seems to be ignored, otherwise the script should abort at the first `sh: 6: [[: not found` error. Line `830` explains the different behaviour. Unless edeliver runs in verbose mode, [it sets](https://github.com/boldpoker/edeliver/blob/59378a62994bd3bd07a12267b2d4f5f824366d82/libexec/erlang-init#L483) `$SILENCE` to `&> /dev/null`. This causes commands like in that line to expand to `cd ${_app_path}/${APP} &> /dev/null` (the `cd` command can sometimes have some output #57). In a POSIX shell this line is interpreted as `cd ${_app_path}/${APP} &; > /dev/null` which means, that the __cd command is started in the background__ because of the ampersand and "nothing" is redirected to `/dev/null`, which means, that the __current shell does not change to that directory__ and the __start script will not be found__. In verbose mode, `$SILENCE` is just empty and the cd command works. So the contents of `$SILENCE` in non-vebose mode needs to change to either `1&> /dev/null` or `> /dev/null`. POSIX shells don't support [double brackets](http://mywiki.wooledge.org/BashFAQ/031) in conditions, which means no support for negations (`!`), conditional evaluation (`&&`, `||`), expression grouping, regexp matching etc. That's why you see a lot of `[[: not found` error messages. 

But we will try to make the scripts on the deploy hosts POSIX compatible. See #143
