### ISSUE TITLE
Ecto migrations on version change?

### ISSUE THREAD

**Issue by shankardevy** [boldpoker/edeliver#15]
One of the hard problem that I am unable to solve is running ecto migration when updating the code. does edeliver have any nice solution for it? thanks

**Comment by bharendt** [comment]
At the moment it's not built-in. But there are two possible ways to add it:

 - Option A: if you want to run the migration automatically __when installing the upgrade__
 - Option B: if you want to run the migration as __edeliver command__

In both cases you __need to add a simple function to one of your modules__, e.g. you `Repo` module which does the migration and doesn't need any arguments or just a single argument, e.g. the name of the migration to apply:

	defmodule YourApplication.Repo do
	  use Ecto.Repo
	  
	  @migrations_dir Path.join([:code.priv_dir(:your_application), "repo", "migrations"])

	  def migrate do
	    Ecto.Migrator.run(__MODULE__, @migrations_dir, :up, [all: true])
	  end
	
	end


#### Run the migration during hot code upgrade (Option A)

  - Build your Upgrade: `edeliver build upgrade --with=old-version`
  - Edit the relup with `edeliver edit relup --version=upgrade-version` and add this instruction: `{apply,{'Elixir.YourApplication.Repo',migrate,[]}}`
   
  - Maybe use a local release store, if `edit relup` doesn't work on remote release store. Default is `.deliver/releases`
  - The __migration__ will then be __executed when you deploy your upgrade__ with `edeliver deploy upgrade`

  
  
#### Add edeliver migrate command (Option B)

To add a custom migrate command to edeliver, e.g. `./edeliver migrate staging|production`, you can add a new edeliver strategy to `./deliver/strategies/erlang-migrate` which looks like that:

	#!/usr/bin/env bash
	source "$(dirname $(dirname $(dirname ${BASH_SOURCE[0]})))/deps/edeliver/libexec/erlang"
	
	[[ $ARGS =~ "production" ]] && export DEPLOY_ENVIRONMENT="production" || export DEPLOY_ENVIRONMENT="staging"    
	set_deploy_hosts

	run() {
	  authorize_hosts
	  status "Migrating ${DEPLOY_ENVIRONMENT} database" 
	  [[ "$DEPLOY_ENVIRONMENT" = "production" ]] && __config_confirm
	  __remote "
	    [ -f ~/.profile ] && source ~/.profile
	    set -e
	    cd ${DELIVER_TO}/${APP} $SILENCE
	    bin/${APP} rpc Elixir.YourApplication.Repo migrate
	  " 
	}


	__config_confirm() {
	  while true; do
	    echo -n -e "\r${2}Are you sure? (y|n): ${txtrst}"
	    read -n 1 option
	    [ "$option" = "y" ] && echo && break
	    [ "$option" = "n" ] && echo && exit 1
	  done  
	}

It is required to __deploy your upgrade first__ before running the `edeliver migrate` command because it contains the migration files.

##### Conclusion:

If there is a simple way how to __get the correct ecto repository module__, we could also add the `edeliver migrate` command directly to edeliver, so that it is available for everybody, if that makes sense. 

The same is required for Option A. Then we could add a `--migrate` flag to the `edeliver build upgrade` command which patches the relup automatically with the ecto migrate instruction.

I will check that, but hope that information from above help you already if you need it right now.

**Comment by shankardevy** [comment]
thank you @bharendt  for your detailed answer. I will try both the options.

**Comment by bharendt** [comment]
Added Option B in the [migrations branch](https://github.com/boldpoker/edeliver/tree/migrations): 

	mix edeliver show migrations 
	mix edeliver migrate up [--version=<migration-id>]

If several __hosts use the same database__, the migrations can be executed only on a single host, if the `--host=[u@]vwx.yz` option is used.

**Comment by alanpeabody** [comment]
@bharendt any plans to push a new version to hex containing this?
