### ISSUE TITLE
Unable to start release

### ISSUE THREAD

**Issue by Valentin-Seehausen** [boldpoker/edeliver#168]
Hey. I have a issue I don't understand.

I can't _start_ my release deployed with edeliver. But I can _console_ or _foreground_ it. When I reset the production machine, I can start it once, but after stopping it,  I cant start it again. The log output doesn't show anything.

I can also start the release from the release store (build host is also staging host), but from the staging dir it wont start.

You can read more about it here: https://github.com/bitwalker/distillery/issues/59

Any ideas? Or hints where I could have a look for log?

Kind regards,
V

**Comment by hamann** [comment]
@Valentin-Seehausen If you set your cookie to something simple without special chars, like

```sh
environment :prod do
  set include_erts: true
  set include_src: false
  set cookie: :"abcdefg"
end
```

then delete `_build` and `~/.erlang.cookie` and rebuild your release, does that solve it?

**Comment by bharendt** [comment]
This behavior [seems to be caused](https://github.com/bitwalker/distillery/issues/59#issuecomment-258928892) by erlang cookies generated as a random default value by distillery, which could contain illegal characters. This resulted in separate cookies used for the release start (default cookie from `$HOME/.erlang.cookie` and the cookie used to connect to the running node (that one with "illegal" characters from the `vm.args`), e.g. for the `ping`, `remote_console` or `stop` command. Closing this issue because that is [fixed already in the distillery project](https://github.com/bitwalker/distillery/commit/2de0611ab6ebecf8c32d5e5ce793a5e6bf112145).

**Comment by Valentin-Seehausen** [comment]
Issue still remains. And `ping` and `stop` do actually work. Only starting after stopping doesn't.

**Comment by sabondano** [comment]
I'm also having the same issue as Valentin-Seehausen : /. Valenting, any luck figuring this out?

**Comment by sabondano** [comment]
@hamann I tried your suggestion (simple cookie (no special characters) then deleting `_build` and `~/.erlang.cookie` (from both the build and the host server) but I still get the same behavior: `ping` and `stop` work but `start` doesn't (the mix edeliver node commands). If I log in to the host server and run `bin/my_app start` it starts fine which then let's me run `mix edeliver ping staging` and `mix edeliver stop staging` successfully (remotely).

Another part I thought could help in diagnosing this issue is that after I delete `~/.erlang.cookie` from the host server (staging in my case) a new cookie is created after I attempt `mix edeliver start staging` remotely.

Anything comes to mind? Thank you so much!

**Comment by sabondano** [comment]
Incase somebody else runs into this problem: my issue was that my application needs an env variable to be set up for it to be able to start. Even though I was setting it manually by login into my host server and setting it, the `mix edeliver start staging` command was using a different process in my staging server (a process without the env variables). I found that because the edeliver start command sources ~/.profile I could make sure that the env variables get set there for the command to work as expected. So if you're reading this and find yourself being able use the ping and stop edeliver node commands, and `bin/my_app start` works when run from your host server but the start edeliver node command doesn't, then this could be your problem. I hope it helps!

**Comment by benrom** [comment]
For me the `edeliver start` command only works from time to time.
I'd say once every 5 to 10 trials. This is annoying.
My `~/.profile` file sources another file containing all the environment variables that are exported. If I login they are loaded correctly (visible with `declare -px`).

There must be some timing issue here, but I don't know where..

**Comment by sabondano** [comment]
@benrom are you using an init script (https://github.com/boldpoker/edeliver/wiki/Example-Init-Scripts)?

**Comment by benrom** [comment]
I added one very recently, but it was the same before.

**Comment by Moxide** [comment]
Hello,
If it could help you, I also faced a LOT of start/restart issues, and the recent `distillery` updates fixed them all ;-)
