### ISSUE TITLE
Specify custom SSH port?

### ISSUE THREAD

**Issue by sheharyarn** [boldpoker/edeliver#19]
The server i'm trying to deploy to, it's ssh port is not 22 and I can't seem to find a way to specify the ssh port in the edeliver configs. So, is there a way to specify the ssh port currently?

**Comment by bharendt** [comment]
Unfortunately __[ssh](http://unixhelp.ed.ac.uk/CGI/man-cgi?ssh+1) does not allow to pass the port number in the url__. Also edeliver allows to use different __deploy paths__ per host, which are __seperated by `:` from the host name__. This would make it __more difficult to parse__ the port number if it would be allowed to include the port number in the url. Using an __environment variable__ like `EDELIVER_SSH_OPTIONS` is also __not so useful__, because ssh command is used for __different kinds of hosts__, e.g. the build host and the deploy host. 

So my recommendation would be to __set the port number__ of the deploy host(s) in the __[ssh config](https://www.freebsd.org/cgi/man.cgi?query=ssh_config&sektion=5)__ like that:

	# contents of $HOME/.ssh/config
	Host deploy.example.com
	    HostName deploy.example.com
	    Port 22000

see: [http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/](http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/)

The __disadvantage__ is, that this have to be __configured on each host you want to deploy from__.
If that is not suitable for you, we could maybe add some lines to edeliver that check if a ssh config file e.g. in `.deliver/ssh_config` exists and uses that config if present. This file could then be added to the repository.

**Comment by sheharyarn** [comment]
Thanks for the details, I'll check it out the article.
