### ISSUE TITLE
Host key verification failed while deploying from remote release store

### ISSUE THREAD

**Issue by mspanc** [boldpoker/edeliver#25]
I've encountered a "Host key verification failed" while deplyoing release from remote release store:

```
vagrant@trusty64:/vagrant$ mix edeliver deploy release to staging

DEPLOYING RELEASE OF AAAA APP TO STAGING HOSTS

-----> Authorizing hosts
-----> Uploading archive of release 0 from remote release store
Host key verification failed.
```

I had to go to my release store server and add manually validate authenticity of the staging hosts.

In my opinion it should be either:
* automated (tell ssh/scp to trust by default - but it does not seem to be secure)
* forwarded to the user, so instead not really useful "Host key verification failed." user can see the question  

```
The authenticity of host 'yourserver.org (46.101.123.123)' can't be established.
ECDSA key fingerprint is 1a:be:d4:6e:fe:03:4f:3e:98:e8:41:f0:28:16:3f:f7.
Are you sure you want to continue connecting (yes/no)?
```

**Comment by bharendt** [comment]
sorry, it took some time to answer, but thanks for posting this. 
you are right, the __automatic "host authorization" for the _release store_ host is missing__, so we will add it.
the host authorization for the build / deploy host(s) was taken from the original [deliver](https://github.com/gerhard/deliver) project and __just authorizes all that hosts__ to __avoid__ the need of __user interaction__. I also think that this makes sense, e.g. to be able to use ci, but I think we could maybe __display information__ about the hosts that were authorized. Or maybe __add__ an __option to automatically authorize all hosts__ and otherwise __authorize__ all hosts interactively __during the first build__. 
On the other hand I don't know how many people really check that fingerprints when ssh asks for its confirmation, especially if you build and deploy in the same network.

**Comment by thomasdola** [comment]
@mspanc , am also facing the same issue , how did you solve yours?
thanks

**Comment by mspanc** [comment]
@thomasdola I just stopped using edeliver. At the moment I use Dokku + Elixir Buildpack for most of my apps. Unless you want to join nodes into cluster it works very well and configuration overhead is minimal.

**Comment by thomasdola** [comment]
That's cool, but am already using edeliver and am not realy sure i can switch right away..
if you can show me how you were able to solve this issue

> I had to go to my release store server and add manually validate authenticity of the staging hosts.

an explanation will be much appreciated..
thanks

**Comment by mspanc** [comment]
I don't remember, that was long time ago. Probably something related to calling ssh-keyscan your-deploy-server on the server that is initiating SSH or something like this.

**Comment by thomasdola** [comment]
i was trying to create know_hosts on the release store host by ssh-keyscan-ing the deploy host and adding the key to the known_hosts but no success.

just release confused right now...
