### ISSUE TITLE
Release build fails with "Failed to detect generated release version at..."

### ISSUE THREAD

**Issue by aaronjensen** [boldpoker/edeliver#36]
I had mix clean and git clean disabled, reenabling them and blowing away my directory has fixed this for now.

This is the relevant portion of the log:

```
[15:58:33][Step 1/1] ==> Generated .appup for booking 1.0.0-608-g47b6e9c -> 1.0.0-582-gf5a86b7
[15:58:38][Step 1/1] ===> relup successfully created!
[15:58:54][Step 1/1] ==> The release for booking-1.0.0-582-gf5a86b7 is ready!
[15:58:54][Step 1/1] ==> You can boot a console running your release with `$ rel/booking/bin/booking console`
[15:58:54][Step 1/1] Failed to detect generated release version at
[15:58:54][Step 1/1] deploy@server.com:/tmp/erlang/app/edge/builds/rel/app/releases/
[15:58:54][Step 1/1]  (B
[15:58:54][Step 1/1] Please set RELEASE_VERSION=x (B
[15:58:54][Step 1/1] Detected several releases: (B
[15:58:54][Step 1/1]  1.0.0-582-gf5a86b7 (B
[15:58:54][Step 1/1]  1.0.0-608-g47b6e9c (B
```

There are a couple interesting things here. One is that we're building a release, not an upgrade, yet it still generates an appup based on the latest version it finds.

I'm guessing that we reset our edge branch which is why it looks like we are building an earlier version.

If I supply `RELEASE_VERSION` set to the same version as `--version` it works when building releases, however if we build an upgrade in the same situation, even with `RELEASE_VERSION` set, it fails with the same type of error.

For now, we have reenabled mix clean and git clean (probably git clean is enough, but we're being safe)

**Comment by bharendt** [comment]
edeliver __cannot detect__ which is the generated release if there are several releases, because maybe just the git hash in the version number changed or as you mentioned an older version e.g. from a different branch is built. So edeliver always __expects only a single release__ tar after building which means that only one single directory `rel/${APP}/releases/${RELEASE_VERSION}` should exist containing the built `${APP}.tar.gz` (for exrm version >= 0.17) .

In addition, __exrm__ always __builds an upgrade__ if a release with a different version exists in `rel/${APP}/releases/${RELEASE_VERSION}`. This __cannot be disabled__, at least at the current exrm version.

That also means, that reenabling __mix clean__ has no effect on that, so you __can disable__ it again if you like.

To avoid always building upgrades and to avoid telling edeliver which version should be copied to the release store by using the `RELEASE_VERSION` environment variable, __I would recommend to adjust `GIT_CLEAN_PATHS`__ in your config, e.g like that: 

```bash
# ./deliver/config
GIT_CLEAN_PATHS=${GIT_CLEAN_PATHS:="rel"}
# or
GIT_CLEAN_PATHS=${GIT_CLEAN_PATHS:="rel/${APP}/releases/*/${APP}.tar.gz"}
```

Cleaning the whole `rel` directory is safer and should not cause much more overhead since the files for the release can still be copied from the `_build` directory, but the other version maybe allows to build upgrades faster.

Are you __building the upgrades with existing releases__ using the `--with=<release-version-from-store>` option? Because it might be that the old release path is still used by edeliver, when using the `--from=<git-tag-or-revision>` together with exrm >= 0.17. Then the release tar of the old version might not be found and we need to fix that in edeliver.

**Comment by bharendt** [comment]
Verified that building the upgrades from an older git tag or version using the `--from=<git-tag-or-revision>` option works also for exrm versions `>= 0.17`.

**Comment by aaronjensen** [comment]
We're using the `--with=<release-version-from-store>` version. I will try out your suggestions, thank you. By the way, I'm looking forward to the new upgrade feature you're working on. We're doing something similar by cating the `start_erl.data` on one of the servers to determine which version it's running.

**Comment by aaronjensen** [comment]
This seems to be working for now, I'll reopen if we run into issues. Thanks!
