### ISSUE TITLE
build upgrades not incrementing versions

### ISSUE THREAD

**Issue by AaronBetterOfficeApps** [boldpoker/edeliver#44]
I am trying build and hot deploy an upgrade from a branch. I use  the following cmd to run the upgrade build task.

`mix edeliver build upgrade --from=0.0.1 --branch=exception_logging --verbose`

To get this cmd to complete successfully I have to bump the version in my mix file or I would get the following error:

```
FAILED 1:

    [ -f ~/.profile ] && source ~/.profile
    set -e
    cd "/data/web/staging-my_app.example.com/my_app"
    [[ -f "my_appt-0.0.2.tar.gz" ]] && rm "my_app-0.0.2.tar.gz"
    [[ -n "releases/0.0.2" ]] && [[ -d "releases/0.0.2" ]] && rm -rf "releases/0.0.2"

```

After bumping the version in the mix file It would finish without errors, but would then download an upgrade as `my_app_0.0.1.upgrade.tar.gz` 

The output at the end of the task:
```
==> All dependencies have appups ready for release!
==> Generated .appup for my_app 0.0.1 -> 0.0.2
===> relup successfully created!
==> The release for my_app-0.0.2 is ready!
==> You can boot a console running your release with `$ rel my_app/bin my_app console`
-----> Removing built release 0.0.2 from remote release directory
-----> Copying release 0.0.1 to local release store
-----> Copying my_app.tar.gz to release store
```

If I tried to deploy the upgrade zipe and it won't change the code running on the server. I was checking this by running a `remote_console` and triing to run new code.

Here is a copy of my config
#!/usr/bin/env bash

APP="my_app" # name of your release
LINK_SYS_CONFIG="/data/shared/sys.config"
RELEASE_DIR="/data/web/staging-myapp.example.com/build/rel/my_app"
RELEASE_VERSION=0.0.2

BUILD_HOST="162.248.180.55" # host where to build the release
BUILD_USER="deploy" # local user at build host
BUILD_AT="/data/web/staging-myapp.example.com/build" # build directory on build host

STAGING_HOSTS="162.248.180.55" # staging / test hosts separated by space
STAGING_USER="deploy" # local user at staging hosts
TEST_AT="/data/web/staging-myapp.example.com/current" # deploy directory on staging hosts. default is DELIVER_TO

PRODUCTION_HOSTS="162.248.180.39" # deploy / production hosts separated by space
PRODUCTION_USER="deploy" # local user at deploy hosts
DELIVER_TO="/data/web/myapp.example.com/current" # deploy directory on production hosts

pre_erlang_clean_compile() {
  status "Running phoenix.digest" # log output prepended with "----->"
  __sync_remote " # runs the commands on the build host
    set -e # fail if any command fails (recommended)
    cd $BUILD_AT # enter the build directory on the build host (required)
    # run your custom task
    APP=\"$APP\" MIX_ENV=\"$TARGET_MIX_ENV\" $MIX_CMD phoenix.digest
  "
}
```

**Comment by bharendt** [comment]
If you use the `--from=0.0.1` option there must be a tag with that name and the version in the `mix.exs` file should be `0.0.1` for that tag. If you want to build an upgrade, the version in the `mix.exs` file must be different, and you have to commit that change. There is no need to push that change to your remote, but it needs to be committed to be pushed to the build host. 

__Usually you don't have to set the `RELEASE_VERSION=` env in your config__. The release version is detected automatically while building. So __you should remove that from your config__. It also __does not work if the `--from=` option is used__ because in that case there are two versions to build, the old one and the new one.

If you built already the `0.0.1` version it is recommended to build the upgrade using the `--with=0.0.1` option instead of the `--from=0.0.1` option. Then the upgrade can be built faster because the older version doesn't have to be built again.

Edeliver does not increment the application version in the `mix.exs` file automatically. That has mainly two reasons: It would be impossible to track then which version is installed if there is no associated commit with that version and it's hard for edeliver to guess how the version should be incremented. But there is a new feature `--auto-version=git` in the [upgrade-command](https://github.com/boldpoker/edeliver/tree/upgrade-command) branch. It appends the git revision to the version from the mix file for each build and you can omit changing the version.

**Comment by bharendt** [comment]
Closing this because edeliver now supports [auto-versioning](https://github.com/boldpoker/edeliver/wiki/Auto-Versioning) (since version `1.2.0`). This allows to automatically append metadata like git revision, git branch, git commit-count etc.
