### ISSUE TITLE
Deploy from different repository

### ISSUE THREAD

**Issue by tokenvolt** [boldpoker/edeliver#47]
Is there a way to build from different git repository or even different VCS? Currently, I assume the build is performed from origin remote, isn't that right?

**Comment by bharendt** [comment]
You __can deploy any git repository__ because edeliver __pushes__ the code from your __local git repository to the build host__. This means that you don't even have to push your local branches or commits to remote before deploying. 

So __you can use any git repository__ for deployment which you checked out locally. 
You can also include other forks / remotes into your local repository as local branch e.g. if you added them using [`git remote add`](https://www.kernel.org/pub/software/scm/git/docs/git-remote.html) and deploy them too.

At the moment edeliver supports only git as version control system.

**Comment by tokenvolt** [comment]
That makes sense. Thanks!
