### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by AdamBrodzinski** [boldpoker/edeliver#48]
I'm getting this error when trying to get my first build going. However, if I use `git config receive.denyCurrentBranch ignore` on the remote server then everything works fine. 

What exactly is this doing and is this the correct thing to do? (i tried it on a test repo).

Also I accidentally entered the above command on my local dev machine, should I undo this somehow?

```
baz|master ⇒ mix edeliver build release --verbose

BUILDING RELEASE OF BAZ APP ON BUILD HOST

-----> Authorizing hosts
-----> Ensuring hosts are ready to accept git pushes
-----> Pushing new commits with git to: root@xxx.xxx.79.224
remote: error: refusing to update checked out branch: refs/heads/master
remote: error: By default, updating the current branch in a non-bare repository
remote: error: is denied, because it will make the index and work tree inconsistent
remote: error: with what you pushed, and will require 'git reset --hard' to match
remote: error: the work tree to HEAD.
remote: error:
remote: error: You can set 'receive.denyCurrentBranch' configuration variable to
remote: error: 'ignore' or 'warn' in the remote repository to allow pushing into
remote: error: its current branch; however, this is not recommended unless you
remote: error: arranged to update its work tree to match what you pushed in some
remote: error: other way.
remote: error:
remote: error: To squelch this message and still keep the default behaviour, set
remote: error: 'receive.denyCurrentBranch' configuration variable to 'refuse'.
To root@xxx.xxx.79.224:/tmp/erlang/baz/builds
 ! [remote rejected] master -> master (branch is currently checked out)
error: failed to push some refs to 'root@xxx.xxx.79.224:/tmp/erlang/baz/builds'

FAILED 1:
git push --tags -f root@xxx.xxx.79.224 master
```

**Comment by bharendt** [comment]
Yes, setting `git config receive.denyCurrentBranch ignore` on the build host is required to push from your local repository to the build host.

In short: there are two versions of repositories:

A "normal repository" to work in, like you have on your local machine. It contains a `.git` subfolder with the repository data and your "working copy" is in the root folder.

The other type of repository is a "bare" repository and it is used to store / share the history only. E.g. that is what is stored on github. It contains the git data in the root folder (and no "working copy").

[Here you can find a more detailed explanation](http://www.saintsjd.com/2011/01/what-is-a-bare-git-repository/). 

Edeliver needs a working copy on the build host to build the project for you.

But since git version `1.6.2 ` [pushing to a working copy is refused by default](https://github.com/git/git/blob/v1.6.2/Documentation/RelNotes-1.6.2.txt#L4-L7). 

That's why it is required to set the option `git config receive.denyCurrentBranch ignore` on the build host since then.

Actually edeliver does [that automatically for you](https://github.com/boldpoker/edeliver/blob/master/libexec/common#L141) when [building](https://github.com/boldpoker/edeliver/blob/master/strategies/erlang-build-release#L13) (the first time), but not if the [folder already existed](https://github.com/boldpoker/edeliver/blob/master/libexec/common#L136).

That's maybe what happened in your case. 

Maybe we should set that config every time before pushing to the build host, not only when pushing the first time.

**Comment by AdamBrodzinski** [comment]
Ahhh ok that clears up a lot, thanks!!

So when I first tried to build I think it complained about there not being a folder... so I manually did a git clone into `/tmp/erlang/baz/builds` and then re-ran build from my local machine and that got me as far as the error above. Is it supposed to pull down the git project for you? Also before that I didn't setup any github SSH key because it was a public project (but now have a key) so  perhaps that was an issue at first too.

At any rate once i figure all of this out I want to make a quick screencast for Elixir newbs like me :smile:

**Comment by bharendt** [comment]
No, it works a little bit different: it doesn't pull down the git project for you (on the build host), but it pushes it from you local machine. It works like this:
            
                                    
```                                    

    Your Computer                    Repository 
                                      (github)
                                         |
                      clone              v
      o  ([]     <----------------------
      | ----- 
      K  | |     ---->|  work / commit
                 <----v
                |
                |
                v    push 
                 -------------->    Build Host
                                (same architecture as)
                                  (deploy hosts)

                                         |  building release 
                                         |  or upgrade
   Release Store           copy          v
 (Your computer or)  <------------------- 
   (AS3 / SCP)

        |   \   \
        |    \   \    deploy
        |     \   \ 
        v      v   v

   Deploy hosts ....

```

So the repository is not pulled on the build host from the remote, but pushed from your local repository to the build host when you build a release or upgrade. 

This allows to build releases without pushing the changes to the remote repository first, e.g. when testing releases first on staging hosts or especially when building and testing hot-code / live upgrades. 

Because of that it is also not required to configure git user and key on the build host.

**Comment by bharendt** [comment]
So this is different to other deploy tools that work often like that:
                                    
```                                    

    Your Computer                    
                                      
                                         
                      clone                
      o  ([]     <--------------------------------   
      | -----                                    ^
      K  | |     ---->  work / commit            |
                 <----v                          |
                |                                |          
                |                                |          
                v    push                        |          
                 --------------------------> Repository 
                                              (github)
                                          /   /  |
                                         /   /   |
                            pull        /   /    |
                                       /   /     |
                                      v   v      v
                                  Deploy Hosts ...
                                      |   |      |
                                      |   |      |
                            build     |   |      |
                                      v   v      v
                                      |   |      |
                            install   |   |      |
                                      v   v      v 

```

**Comment by bharendt** [comment]
This is usefull especially because you need an old release for building an live upgrade:            
                                    
```                                    

    Your Computer                    Repository 
                                      (github)
                                         |
                      clone              v
      o  ([]     <----------------------
      | ----- 
      K  | |     ---->|  work / commit
                 <----v
                |
                |
                v    push 
                 -------------->      Build Host
                                (same architecture as)
                 -------------->    (deploy hosts)
               /  copy old release
              /                          |   building the
             /                           |     upgrade
   Release Store       copy upgrade      v
 (Your computer or)  <------------------- 
   (AS3 / SCP)

        |   \   \
        |    \   \    deploy upgrade
        |     \   \ 
        v      v   v

   Deploy hosts ....

```

**Comment by monicao** [comment]
> No, it works a little bit different: it doesn't pull down the git project for you (on the build host), but it pushes it from you local machine.

Is the code being pushed from the local machine to the build machine using scp?

**Comment by hamann** [comment]
@monicao `git push` is used, with the build host as an additional remote repository

**Comment by bharendt** [comment]
@monicao: no, you build machine does not need a git server. there is no need to configure git on your build host. edeliver adds your build machine [as remote](https://github.com/boldpoker/edeliver/blob/master/libexec/common#L130) and uses the [ssh protocol](https://git-scm.com/book/tr/v2/Git-on-the-Server-The-Protocols#The-SSH-Protocol) to push the source code of your app there. you can check that by running `git remote -v show` in you project directory after building on the deploy host. It shows something like that:

```sh
$ git remote -v show
$BUILD_USER@$BUILD_HOST $BUILD_USER@$BUILD_HOST:$BUILD_AT (fetch)
$BUILD_USER@$BUILD_HOST $BUILD_USER@$BUILD_HOST:$BUILD_AT (push)
origin git@your_remote(fetch)
origin git@your_remote(push)
```


`$BUILD_USER@$BUILD_HOST:$BUILD_AT` is [the shorter scp-like syntax for the SSH protocol](https://git-scm.com/book/tr/v2/Git-on-the-Server-The-Protocols#The-SSH-Protocol).

**Comment by dustinfarris** [comment]
@AdamBrodzinski are you still getting errors?  can this be closed?

**Comment by AdamBrodzinski** [comment]
Ah sorry, using Heroku now. I'll close this out!
