### ISSUE TITLE
`--increment-version` option breaks `relup` file

### ISSUE THREAD

**Issue by gaynetdinov** [boldpoker/edeliver#65]
Hello.

I've just noticed that if I set `--increment-version` option in the `upgrade` command, generated `relup` file would contain incorrect references to the old release. 

This is beginning of the generated `relup` file of the `upgrade` which I generated with `--increment-version=minor`:
```
{"0.1.0+deploy-with-edeliver-fc42ded",
 [{"0.1.0+deploy-with-edeliver-1c05295",[],
```

The problem here is that previous release also got version bump here. Currently deployed release called  **0.0.1**+deploy-with-edeliver-1c05295, not **0.1.0**+deploy-with-edeliver-1c05295, only the new release should get a version bump. Since there is no release with **0.1.0**+deploy-with-edeliver-1c05295 name, `mix edeliver deploy upgrade` got broken.

**Comment by gaynetdinov** [comment]
If login to remote host, go to `/path/to/my_app/releases/0.1.0+deploy-with-edeliver-fc42ded/` and manually replace wrong references(0.1.0+deploy-with-edeliver-1c05295 with correct 0.0.1+deploy-with-edeliver-1c05295) in `relup` file and then run `./bin/user_settings_service upgrade 0.1.0+deploy-with-edeliver-fc42ded` manually, everything works.

**Comment by bharendt** [comment]
This is true. If you use the `--increment-version=` option, edeliver increments the version for the current build. If you build an upgrade and cannot provide the old release (using the `--with=`) option, but need to build also the old release (using the `--from=` option), the version for the old release would also be incremented while building. It is recommended to use the old release to build an upgrade (whenever it is available), but even though, it is not the wanted behaviour, that the version for the old release which is built is also incremented. I think this also applies for the `--set-version=` option. So thanks for the report. [This commit should fix that](https://github.com/boldpoker/edeliver/commit/466cedc935ef452130b9f385c26c87078708a0ec):

**Comment by gaynetdinov** [comment]
Here https://github.com/boldpoker/edeliver/issues/67 you mentioned that an `upgrade` contains a full release + files for upgrade. Does it mean that I can provide an `upgrade` for `--with` option?

**Comment by gaynetdinov** [comment]
Well, I tried to specify an `upgrade` for `--with` option and it worked :) So maybe it would make sense to change README as well? Because currently it says that only release can be provided for `--with` option.

**Comment by bharendt** [comment]
Yes, you can use also upgrades for the `--with=` option when using exrm as tool to build the releases / upgrades. But e.g. when using rebar, only the changed files are included into the upgrade package and these upgrades cannot be used.

I [updated the README](https://github.com/boldpoker/edeliver/commit/114a0b4ac799a8a0ca840f7a1586962c1907d55e), added that information and also changed the `upgrade` section to make it more clear, that the `--with=` option is that what you normally want to use and that the `--from=` option is only necessary if the old release (or upgrade package) is not available any more. So thanks for the hint. 

And by writing this I also think it would make sense to add something like `--with=running`, which generates (repackages) a release from a running node and downloads it to the build host when building the upgrade, which would be much faster as to build it from an old revision. And that should always be available, otherwise it also would not make sense to build and deploy a hot code upgrade for that version anyway.

**Comment by gaynetdinov** [comment]
Yeah, that would be awesome. Thanks for all your work and help!
