### ISSUE TITLE
Found several ecto repository modules

### ISSUE THREAD

**Issue by monicao** [boldpoker/edeliver#70]
I am deploying a phoenix application using `edeliver 1.2.3`, `ecto 1.1.4`, `swoosh 0.3.0`.

```
mix edeliver show migrations on production
```

Returns the following error

```
  response: ==> Found several ecto repository modules ([MyApp.Mailer, MyApp.Repo]).
    Please specify the repository to use in the edeliver config as ECTO_REPOSITORY env.
<<"error">>
```

The MyApp.Mailer module looks like this. I am using swoosh to send email https://github.com/swoosh/phoenix_swoosh

```
defmodule MyApp.Mailer do
    use Swoosh.Mailer, otp_app: :designdrop
end
```

It looks like the Swoosh.Mailer is being picked up as a potential ecto repo.

I tried setting the ECTO_REPOSITORY environment variable on my local machine before running the command: `ECTO_REPOSITORY="MyApp.Repo" mix edeliver show migrations on production`, but this didn't work.

Tried exporting the ECTO_REPOSITORY in the `~/.profile` file on the production machine, but that didn't work either.

Tried adding "ECTO_REPOSITORY="MyApp.Repo" to the `.deliver/config` file. No luck.

The message "Please specify the repository to use in the edeliver config as ECTO_REPOSITORY env." is a bit confusing.

How should I export this environment variable?

**Comment by bharendt** [comment]
Thanks for the detailed report. You are right: when using the `ECTO_REPOSITORY` env it must be set on your local machine, which means you could pass it to the edeliver command like this `ECTO_REPOSITORY="MyApp.Repo" mix edeliver show migrations`, or setting it in your local `.deliver/config` or `~/.profile` file. 

The env should be set [here](https://github.com/boldpoker/edeliver/blob/master/strategies/erlang-node-execute#L200) and actually used [here](https://github.com/boldpoker/edeliver/blob/master/lib/edeliver.ex#L49) in the edeliver code. What error do you get if you set the `ECTO_REPOSITORY` env, the same one or [that one](https://github.com/boldpoker/edeliver/blob/master/lib/edeliver.ex#L55)?

To identify the ecto repository module, edeliver searches for a module which exports the `__repo__` function. Because this function is removed in ecto `2.0` it also looks for modules which export the `__adapter__` function. Maybe you can check whether your module exports one of these functions. See [edeliver.ex:70](https://github.com/boldpoker/edeliver/blob/master/lib/edeliver.ex#L70).

Maybe we could exetend the searchcriteria by also checking the arity of the function of find a better way, how to identify the ecto repository module.

**Comment by bharendt** [comment]
It looks like the false identification as ecto repository module is caused by the [`__adapter__` function](https://github.com/swoosh/swoosh/blob/4f3ed760aa8c6bd3c6e8f2d952ecea9575a6fddd/lib/swoosh/mailer.ex#L66) from the `Swoosh.Mailer` module. As a quick solution you could use the edeliver version `1.2.3` without the ecto `2.0` support, but I think we should maybe find a better solution for identifying ecto repsitories in general or improve it by checking also other properties of the module. Any ideas @talklittle?. See also #61 and #50.

**Comment by bharendt** [comment]
Sorry, just saw that you mentioned that your are using edeliver version `1.2.3` (and not `1.2.4`). But then the `__adapter__` function from the `Swoosh.Mailer` module could not be the cause for detecting the `MyApp.Mailer` wrongly as ecto repository. @monicao, could you maybe verify which exact edeliver version you are using and maybe also provide the output of the `MyApp.Repo.module_info(:exports)` function?

**Comment by talklittle** [comment]
Gonna assume they are indeed using 1.2.4 using `"~> 1.2.3"` in mix.exs

Instead of looping through modules and looking for specific exports, maybe we can somehow utilize the new Ecto 2.0 requirement of specifying your Ecto Repos in the config.exs?

    config :my_app, ecto_repos: [MyApp.Repo]

As mentioned at http://blog.plataformatec.com.br/2016/04/ecto-2-0-0-rc-is-out/

**Comment by monicao** [comment]
Thanks so much for the quick reply! 

I double checked and you are right I am using `edeliver 1.2.4`.

**Comment by monicao** [comment]
@bharendt Unfortunately using edeliver 1.2.3 did not work. Here are my steps:

- Updated mix.exs to require `{:edeliver, "1.2.3"}`
- `mix deps.clean edeliver`
- `mix deps.get`
- Checked that `deps/edeliver/mix.exs` has version 1.2.3
- Updated the version in my app's `mix.exs` and built a new release with edeliver. 
- Checked that the build machine is using edeliver version 1.2.3 (BUILD_AT/deps/edeliver/mix.exs has version 1.2.3)
- `mix edeliver deploy release to production`
- `mix edeliver ping production` returns pong, so all good there.

- `mix edeliver migrate production up` returns the ` response: ==> Found several ecto repository modules ([Designdrop.Mailer, Designdrop.Repo]).
    Please specify the repository to use in the edeliver config as ECTO_REPOSITORY env.`
- `ECTO_REPOSITORY="Designdrop.Repo" mix edeliver migrate production up` returns the same error as above.

Any idea what went wrong?

**Comment by talklittle** [comment]
@monicao Did you try `mix edeliver stop production` followed by `mix edeliver start production` to ensure the previous release isn't still running on production?

Anyway, I submitted PR #71 which hopefully fixes the issue.

**Comment by monicao** [comment]
Thanks @talklittle that was it!

**Comment by bharendt** [comment]
@talklittle: If ecto `2.0` requires to specify the repository module in the config, I also think this is the best way to get the module name. So thank you very much for adding that and providing a pull request.

**Comment by bharendt** [comment]
@monicao: you were right, the `ECTO_REPOSITORY` env was ignored for the `edeliver show migrations` and the `edeliver migrate` tasks because the migration is executed on the node by a rpc call, which means that only `ECTO_REPOSITORY` envs that were set when the node was started were considered. This [commit should fix that](https://github.com/boldpoker/edeliver/commit/4230fd33a202ea8fe9f60197f3da52b1a35f7776):

**Comment by bharendt** [comment]
This changes are included in the [edeliver hex package 1.2.5](https://hex.pm/packages/edeliver/1.2.5). Thanks.

**Comment by monicao** [comment]
Verified that setting the environment variable works in version `1.2.5`.

Just in case anyone else runs into this: I had to prepend `Elixir` to the repo module name.

```
ECTO_REPOSITORY="Elixir.MyApp.Repo" mix edeliver migrate production
```

**Comment by speeddragon** [comment]
I'm using the last version of edeliver, `1.7.0` and using `ECTO_REPOSITORY="Elixir.MyApp.Repo" mix edeliver migrate production` didn't work for me.
