### ISSUE TITLE
How do we set environment variables on the server?

### ISSUE THREAD

**Issue by aaronjensen** [boldpoker/edeliver#75]
We need to set `RELEASE_CONFIG_FILE` and `VMARGS_PATH` on the server. They're set in .profile, so a `bash -l` would get them, but I don't know how to set them for edeliver operations.

**Comment by bharendt** [comment]
Setting it in the `.profile` on the deploy hosts should actually work, because edeliver sources that file for all the commands, like [here](https://github.com/boldpoker/edeliver/blob/23cdf71605d9f15b4716492c909862b8f4e30512/libexec/erlang#L784). For which edeliver command(s) does it fail? 
Do you have to set it because of the autogenerated `/running-config` dir?

**Comment by aaronjensen** [comment]
Sorry, actually it's actually in our `/etc/profile`

**Comment by aaronjensen** [comment]
and we have it set because we override vm.args and a conform config w/ chef. I just came across `LINK_VM_ARGS` so I'm going to try that as well as writing my own plugin to link the conform config

**Comment by aaronjensen** [comment]
Oh, and lots of stuff fails. For example:

```
mix edeliver ping staging

EDELIVER BOOKING WITH PING COMMAND

-----> pinging staging servers

staging node:

  user    : deploy
  host    : mysite.com
  path    : /var/www
  response: Node 'booking@edge-bigger' not responding to pings.

PING DONE!
```

In my vm.args the node name is changed. Even if I linked the vm.args, this still fails. I think changing our node name has broken edeliver :/

**Comment by aaronjensen** [comment]
Update: setting `RELEASE_CONFIG_FILE` and `VMARGS_PATH` in `.profile` works, so I'll just do that for now.

**Comment by aaronjensen** [comment]
For now, we're going to source `/etc/profile` from our `.profile`, but I think that edeliver should source `/etc/profile` as well

**Comment by bharendt** [comment]
The pro would be that this is also what bash does for an interactive login shell. From the bash man-pages:

> When bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first  reads and  executes  commands from the file /etc/profile, if that file exists.  After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that  exists  and  is readable.  The --noprofile option may be used when the shell is started to inhibit this behavior.

But the cons are, that

 - this would not be backwards compatible
 - strictly speaking this would also require to source `~/.bash_profile` and `~/.bash_login` in addition
 - sourcing any of that files increases the risk of [hard to debug failures](https://github.com/boldpoker/edeliver/issues/14#issuecomment-105603593) if any of them does not exit with status code `0`
 - sourcing the `~/.profile` is actually used just to be able to set fixed environment variables for the build or deploy commands on the host(s), not to simulate the whole login environment when executing remote commands via ssh.

So if it works for you now, I would like to postpone that decision. 

And you might need check whether your solution might cause trouble when logging in on that host, because the `/etc/profile` would then be sourced twice by bash.

**Comment by dustinfarris** [comment]
I am also hitting this.  It is because I am installing erlang/elixir on my build server using [asdf](https://github.com/asdf-vm/asdf) which installs local to the build user.  So mix is also local to the user.

If edeliver can't invoke an interactive shell, is there a way to specify the full location of mix (and any other binary required)?

**Comment by dustinfarris** [comment]
I was able to add the following to my config:

```
BUILD_CMD="/home/builder/.asdf/shims/mix"
```

that got me a little further, but it then breaks down here:

```
-----> Fetching / Updating dependencies
-----> Compiling sources
-----> Detecting exrm version
bash: line 3: mix: command not found
bash: line 4: mix: command not found
cat: deps/exrm/mix.exs: No such file or directory

Failed to detect exrm version.
```

**Comment by bharendt** [comment]
@dustinfarris: I think you get this error, because the `mix` command is found now which you set in `MIX_CMD`, but the `mix` script [does not find the elixir binary now](https://github.com/elixir-lang/elixir/blob/master/bin/mix#L1). Didn't it work to add `~/.asdf/shims` to the `$PATH` in `~/.profile`?

**Comment by dustinfarris** [comment]
No.  ~/.profile is not sourced :-(

**Comment by dustinfarris** [comment]
If I put the directories in /etc/environment it works, but that's really dirty would rather not have to do that.

**Comment by hamann** [comment]
@dustinfarris I'm also using asdf on a build host. For that I added `. /home/deploy/.asdf/asdf.sh` to `~/.profile` and everything works as expected.

**Comment by dustinfarris** [comment]
@hamann my .profile has `. "$HOME/.bashrc"` and .bashrc has `. /home/builder/.asdf/asdf.sh` so i think it should work, but it doesn't, i will try putting it directly in .profile

**Comment by hamann** [comment]
@dustinfarris if your .bashrc contains the following
```sh
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```
nothing will happen after that. Sourcing .bashrc in .profile is a bad idea

**Comment by dustinfarris** [comment]
@hamann sourcing .bashrc in .profile is default behavior on ubuntu, but i'm thinking it is being negated because edeliver is not using a bash shell (maybe) so i'm thinking you are right, this belongs in .profile.  I am testing now.

**Comment by dustinfarris** [comment]
Yes, putting it in .profile works.  Thanks @hamann
