### ISSUE TITLE
Option to have DELIVER_TO be full path

### ISSUE THREAD

**Issue by aaronjensen** [boldpoker/edeliver#92]
At the moment, edeliver actually delivers to `$DELIVER_TO/$APP`. It'd be nice if it would respect `$DELIVER_TO` as the full path--this was confusing for me at first, and now that we're attempting to get blue/green deploys working, it means that I have an extra directory that I don't want, like `/var/www/my_app/next/my_app`. Ideally I could simply deploy to `/var/www/my_app/next`. I know that this would be a breaking change, and it may not be desirable by all if they share a config across multiple apps and expect `$DELIVER_TO` to act as it does today.

**Comment by bharendt** [comment]
This is due to the fact, that erlang releases which were generated by rebar contain the application name as subdir in the release/upgrade tar. 

Also upgrades generated by exrm require an `$APP` subdir. They [need to be deployed to the parent dir](https://github.com/boldpoker/edeliver/blob/c428d7ed6af1d42862e538ce1a9573b7c2815718/libexec/erlang#L670) of the `$APP` sub dir before being installed on a running node.

**Comment by aaronjensen** [comment]
ok, that makes sense. I'll close this out, we worked around it.
