### ISSUE TITLE
Race condition when detecting version of starting app

### ISSUE THREAD

**Issue by aaronjensen** [boldpoker/edeliver#93]
The new `update` command starts the app and then immediately does an rpc call. This often causes:

```bash
$ bin/booking rpc Elixir.Edeliver run_command '[[release_version, "booking"]].'
RPC to 'staging-green@127.0.0.1' failed: {'EXIT',
                                          {{badmatch,nil},
                                           [{'Elixir.Edeliver',run_command,1,
                                             [{file,"lib/edeliver.ex"},
                                              {line,27}]},
                                            {rpc,
                                             '-handle_call_call/6-fun-0-',5,
                                             [{file,"rpc.erl"},{line,206}]}]}}
```

Which gives the opaque error:

```
[10:38:53]Checking updated version on host deploy@staging.curadora.com
[10:38:53]Version [{file,rpc.erl},{line,206}]}]}} is installed on host deploy@mysite.com
[10:38:53]
[10:38:53]Node on deploy@mysite.com was not updated. Still running version                                              [{file,rpc.erl},{line,206}]}]}}.
```

I can reproduce this manually by doing a `start` followed by the rpc call.

Edeliver needs to either poll or wait long enough for the application to start. I'm not sure if `Application.ensure_all_started/2` would be appropriate here or not.

**Comment by bharendt** [comment]
Are you using edeliver version >= `1.2.8`? Since that version the release should be started synchronously, so the start command should return `:ok` only after all applications in the release were started. But this __requires to add edeliver as last application__ (which will be started) to the the list of included (and running) applications in the `mix.exs` file. Calling `Application.ensure_all_started/2` here would not help in that case, because it does not block until the startup progress is finished, but tries to start all applications and returns after they were started. So this would cause a race condition by starting them a second time.

**Comment by aaronjensen** [comment]
We are using 0512323d266d383c615181e7e3fcfc7a6dfe3f83 which is after the commit you linked. We didn't have edeliver as the last application, however. I missed that change in the readme. I'll try that out, thanks.

**Comment by aaronjensen** [comment]
So far so good on this change, I'll close it out. Thanks!

**Comment by aaronjensen** [comment]
This is still happening on our slower machine.

**Comment by bharendt** [comment]
With the same error?

**Comment by aaronjensen** [comment]
Yes. I think the problem is that my application takes a while to start, so even if edeliver starts, my application is still in the process of starting.

**Comment by bharendt** [comment]
If edeliver is the last application in the list of applications to start, your application actually must have been started when the edeliver application started. Maybe you could retry with only one server and use the `--verbose` flag. Then you should be able to see the startup progress of all included apps if the start of the release takes more than ~2 seconds.
