### ISSUE TITLE
Sometimes deploy command wants to deploy release 0

### ISSUE THREAD

**Issue by gaynetdinov** [boldpoker/edeliver#99]
Hello.

Sometimes when I have only one release to deploy in `.deliver/releases` folder, `deploy` command goes crazy and wants to deploy release 0.

```sh
$ mix edeliver deploy release to qa1                                                                                                
DEPLOYING RELEASE OF MY_APP APP TO QA1 HOSTS

-----> Authorizing hosts
-----> Uploading archive of release 0 from local release store
copying .deliver/releases/my_app_0.0.1+master-01b4601.release.tar.gz to user@myhost.com:/home/user/my_app/my_app_0.tar.gz
```

Unfortunately I don't have any other hints how to reproduce this bug, but seems like it happens when there is only one suitable release to deploy. If I run `mix edeliver deploy release to qa1 --version=` and specify a proper version, it works.

**Comment by bharendt** [comment]
True. It looks like the version is detected wrongly if there is only one single release in the store. It was able to reproduce it, even if I see a slightly different `Uploading archive of release 1 ` message instead of `... release 0`. Unpacking (and even starting the release when the `--start-deploy` is used) still works correctly in that case, because the content of the release does not change, only the name on the deploy host(s). This happens [when the version is extracted from the found file name](https://github.com/boldpoker/edeliver/blob/4de6d7dcb2738dd311f4b7c31033b88eacd07db0/libexec/erlang#L539) and the `$_release_type` is set to `*` when using exrm as release tool, because for exrm also built upgrades can be deployed as release. Thanks for the report, I think this commit should fix that:

**Comment by gaynetdinov** [comment]
It works. Thanks!
